# Generated by Django 5.2.3 on 2025-06-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("articul", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Название Товара"),
                ),
                ("brand", models.CharField(blank=True, max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discounted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("rating", models.FloatField()),
                ("review_count", models.IntegerField()),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Все товары",
            },
        ),
    ]
